apiVersion: v1
kind: Pod
metadata:
  name: esdhbackend
  labels:
    app: esdhbackend
spec:
  containers:
    - name: esdhbackend
      image: kjcontaineres.azurecr.io/esdhdemo_backend:latest
      ports:
        - containerPort: 5047
---
apiVersion: v1
kind: Pod
metadata:
  name: esdhfrontend
  labels:
    app: esdhfrontend
spec:
  containers:
    - name: esdhfrontend
      image: kjcontaineres.azurecr.io/esdhdemo_frontend:latest
      env:
        - name: REACT_APP_ENDPOINT
          value: "http://51.105.107.230:5047"
      ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: esdhfrontend
  ports:
    - port: 3000
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: esdhbackend
  ports:
    - port: 5047
      targetPort: 5047
  type: LoadBalancer
