apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-myservicea
spec:
  rules:
    - http:
        paths:
          - path: /Api
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 5047
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 3000

  ingressClassName: nginx
